name: Hospital Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Versión estable y compatible con tus dependencias

    - name: Instalar dependencias
      run: npm install

    - name: Construir la aplicación (Vite Build)
      run: npm run build

    # --- PASOS DE DOCKER HUB ---
    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir y Subir imagen Docker
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hospital-frontend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hospital-frontend:latest